version: 2.1

orbs:
  slack: circleci/slack@5.1.1

# this is general circleCI implementation.
# This file might need some changes after setting up project for functional CICD
jobs:
  build:
    docker:
      - image: cimg/go:1.22

      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: p@ssw0rd

    parallelism: 1
    working_directory: ~/go/src/github.com/readytowork-org/boilerplate-api

    steps:
      - checkout

      - run:
          name: Initialize the environment variable file
          command: |
            echo "ENVIRONMENT=local
            HOST=$HOST
            DB_HOST=localhost
            DB_PORT=3306
            DB_NAME=test_db
            DB_USERNAME=test_user
            DB_PASSWORD=p@ssw0rd
            MAIL_CLIENT_ID=$MAIL_CLIENT_ID
            MAIL_CLIENT_SECRET=$MAIL_CLIENT_SECRET
            MAIL_REFRESH_TOKEN=$MAIL_REFRESH_TOKEN
            STORAGE_BUCKET_NAME=$STORAGE_BUCKET_NAME
            SENTRY_DSN=$SENTRY_DSN " > .env

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Waiting for MYSQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run:
          name: Initialize firebase service account key file
          command: |
            echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > serviceAccountKey.json

      - run:
          name: Build repo
          command: |
            go build main.go

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "go/pkg/mod"

      - run:
          name: Start the service
          command: ./main
          background: true

      - run:
          name: Validate if the service is working or not.
          command: |
            sleep 5
            curl http://localhost:8080/health-check

      - slack/notify:
          event: pass
          template: basic_success_1

      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: 'develop'

  deploy_to_develop:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Append GAR beta settings app yml
          command: |
            echo -e "beta_settings:\n  cloud_sql_instances: $DB_HOST" >> app.yml

      - run:
          name: Initialize the environment variable file
          command: |
            echo "ENVIRONMENT=$ENVIRONMENT
            HOST=$HOST
            DB_HOST=$DB_HOST
            DB_PORT=$DB_PORT
            DB_NAME=$DB_NAME
            DB_USERNAME=$DB_USERNAME
            DB_PASSWORD=$DB_PASSWORD
            MAIL_CLIENT_ID=$MAIL_CLIENT_ID
            MAIL_CLIENT_SECRET=$MAIL_CLIENT_SECRET
            MAIL_REFRESH_TOKEN=$MAIL_REFRESH_TOKEN
            STORAGE_BUCKET_NAME=$STORAGE_BUCKET_NAME
            SENTRY_DSN=$SENTRY_DSN " > .env

      - run:
          name: Initialize firebase service account key file
          command: |
            echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > serviceAccountKey.json

      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}

      - deploy:
          name: Deploy to Google App Engine
          command: |
            gcloud app deploy app.yaml --project $GCLOUD_PROJECT_ID  --quiet

      - deploy:
          name: Deploy CRON to Google App Engine Cloud Scheduler
          command: |
            gcloud app deploy cron.yaml --quiet

      - run:
          name: Delete Old versions of App Engine
          command: |
            versions=$(gcloud app versions list \
              --service default \
              --sort-by '~VERSION.ID' \
              --format 'value(VERSION.ID)' | sed 1,5d)
            for version in $versions; do
              gcloud app versions delete "$version" \
                --service default \
                --quiet
            done

      - run:
          name: Retrieve Commit Message
          command: |
            # Try to extract the body of the commit message
            COMMIT_MESSAGE=$(git log -1 --pretty=%b)
            # Fallback to the subject if the second is empty
            if [ -z "$COMMIT_MESSAGE" ]; then
              COMMIT_MESSAGE=$(git log -1 --pretty=%s)
            fi
            echo "export COMMIT_MESSAGE='${COMMIT_MESSAGE}'" >> $BASH_ENV

      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                  {
                      "type": "header",
                      "text": {
                          "type": "plain_text",
                          "text": "Job Succeeded. :white_check_mark:",
                          "emoji": true
                      }
                  },
                  {
                      "type": "section",
                      "fields": [
                          {
                              "type": "mrkdwn",
                              "text": "*Job*: ${CIRCLE_JOB}"
                          },
                          {
                              "type": "mrkdwn",
                              "text": "*Project*: ${CIRCLE_PROJECT_REPONAME}"
                          }
                      ]
                  },
                  {
                      "type": "section",
                      "fields": [
                          {
                              "type": "mrkdwn",
                              "text": "*Commit*: ${CIRCLE_SHA1}"
                          },
                          {
                              "type": "mrkdwn",
                              "text": "*Author*: ${CIRCLE_USERNAME}"
                          }
                      ]
                  },
                  {
                      "type": "section",
                      "fields": [
                          {
                              "type": "mrkdwn",
                              "text": "*Branch*: ${CIRCLE_BRANCH}"
                          },
                          {
                              "type": "mrkdwn",
                              "text": "*Title*: ${COMMIT_MESSAGE}"
                          }
                      ]
                  },
                  {
                      "type": "actions",
                      "elements": [
                          {
                              "type": "button",
                              "text": {
                                  "type": "plain_text",
                                  "text": "View Job",
                                  "emoji": true
                              },
                              "url": "${CIRCLE_BUILD_URL}"
                          }
                      ]
                  }
              ]
            }

      - slack/notify:
          event: fail
          template: basic_fail_1

  deploy_to_production:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Append GAR beta settings app yml
          command: |
            echo -e "beta_settings:\n  cloud_sql_instances: $DB_HOST" >> app.yml

      - run:
          name: Initialize the environment variable file
          command: |
            echo "ENVIRONMENT=$ENVIRONMENT
            HOST=$HOST
            DB_HOST=$DB_HOST
            DB_PORT=$DB_PORT
            DB_NAME=$DB_NAME
            DB_USERNAME=$DB_USERNAME
            DB_PASSWORD=$DB_PASSWORD
            MAIL_CLIENT_ID=$MAIL_CLIENT_ID
            MAIL_CLIENT_SECRET=$MAIL_CLIENT_SECRET
            MAIL_REFRESH_TOKEN=$MAIL_REFRESH_TOKEN
            STORAGE_BUCKET_NAME=$STORAGE_BUCKET_NAME
            SENTRY_DSN=$SENTRY_DSN " > .env

      - run:
          name: Initialize firebase service account key file
          command: |
            echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > serviceAccountKey.json

      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}

      - deploy:
          name: Deploy to Google App Engine
          command: |
            gcloud app deploy app.yaml --project $GCLOUD_PROJECT_ID --quiet

      - deploy:
          name: Deploy CRON to Google App Engine Cloud Scheduler
          command: |
            gcloud app deploy cron.yaml --quiet

      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - boilerplate_dev
            - rtw_basic
          filters:
            branches:
              only:
                - develop
                - main

      - deploy_to_develop:
          context:
            - boilerplate_dev
            - rtw_basic
          filters:
            branches:
              only:
                - develop
          requires:
            - build

      - deploy_to_production:
          context:
            - boilerplate_production
            - rtw_basic
          filters:
            tags:
              only:
                - /v[0-9].*/
            branches:
              ignore:
                - /.*/
