#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "Starting precommit hook -----------"
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against --

# Get the list of staged Go files
GO_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '.go$')
NORMAL=$(tput sgr0)
LIME_YELLOW=$(tput setaf 190)

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)


if [ -n "$GO_FILES" ]; then
  # Run gofmt on each staged Go file
    for FILE in $GO_FILES; do
        $(go env GOPATH)/bin/golangci-lint run $FILE
        if [[ $? != 0 ]]; then
            printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
            exit 1
        fi
        gofmt -w $FILE
    done

  # Add the formatted files back to the staging area
	git add $GO_FILES

  	echo "Go code formatting applied successfully."
fi
